In [ ]:
# Задание 1. Напишите функцию, которая возвращает название валюты (поле ‘Name’) с максимальным значением курса с помощью сервиса https://www.cbr-xml-daily.ru/daily_json.js

In [10]:
import requests

class Rate:
    def __init__(self, format_='value'):
        self.format = format_
    
    def exchange_rates(self):
        
        r = requests.get('https://www.cbr-xml-daily.ru/daily_json.js')
        return r.json()['Valute']
    
    def make_format(self, currency):
       
        response = self.exchange_rates()
        
        if currency in response:
            if self.format == 'full':
                return response[currency]
            
            if self.format == 'value':
                return response[currency]['Value']
        
        return 'Error'
    
    def eur(self):
        
        return self.make_format('EUR')
    
    def usd(self):
        
        return self.make_format('USD')

In [12]:
r = Rate(format_='full')

In [13]:
r.exchange_rates()

{'AUD': {'ID': 'R01010',
  'NumCode': '036',
  'CharCode': 'AUD',
  'Nominal': 1,
  'Name': 'Австралийский доллар',
  'Value': 58.7462,
  'Previous': 58.8281},
 'AZN': {'ID': 'R01020A',
  'NumCode': '944',
  'CharCode': 'AZN',
  'Nominal': 1,
  'Name': 'Азербайджанский манат',
  'Value': 45.4183,
  'Previous': 45.3803},
 'GBP': {'ID': 'R01035',
  'NumCode': '826',
  'CharCode': 'GBP',
  'Nominal': 1,
  'Name': 'Фунт стерлингов Соединенного королевства',
  'Value': 105.7633,
  'Previous': 105.9369},
 'AMD': {'ID': 'R01060',
  'NumCode': '051',
  'CharCode': 'AMD',
  'Nominal': 100,
  'Name': 'Армянских драмов',
  'Value': 14.4928,
  'Previous': 14.4249},
 'BYN': {'ID': 'R01090B',
  'NumCode': '933',
  'CharCode': 'BYN',
  'Nominal': 1,
  'Name': 'Белорусский рубль',
  'Value': 29.2018,
  'Previous': 28.9473},
 'BGN': {'ID': 'R01100',
  'NumCode': '975',
  'CharCode': 'BGN',
  'Nominal': 1,
  'Name': 'Болгарский лев',
  'Value': 46.9064,
  'Previous': 46.8358},
 'BRL': {'ID': 'R01115',
  'NumCode': '986',
  'CharCode': 'BRL',
  'Nominal': 1,
  'Name': 'Бразильский реал',
  'Value': 13.8583,
  'Previous': 13.7347},
 'HUF': {'ID': 'R01135',
  'NumCode': '348',
  'CharCode': 'HUF',
  'Nominal': 100,
  'Name': 'Венгерских форинтов',
  'Value': 25.5774,
  'Previous': 25.5382},
 'HKD': {'ID': 'R01200',
  'NumCode': '344',
  'CharCode': 'HKD',
  'Nominal': 10,
  'Name': 'Гонконгских долларов',
  'Value': 99.2064,
  'Previous': 99.0597},
 'DKK': {'ID': 'R01215',
  'NumCode': '208',
  'CharCode': 'DKK',
  'Nominal': 1,
  'Name': 'Датская крона',
  'Value': 12.3349,
  'Previous': 12.3194},
 'USD': {'ID': 'R01235',
  'NumCode': '840',
  'CharCode': 'USD',
  'Nominal': 1,
  'Name': 'Доллар США',
  'Value': 77.1657,
  'Previous': 77.1011},
 'EUR': {'ID': 'R01239',
  'NumCode': '978',
  'CharCode': 'EUR',
  'Nominal': 1,
  'Name': 'Евро',
  'Value': 91.7809,
  'Previous': 91.6192},
 'INR': {'ID': 'R01270',
  'NumCode': '356',
  'CharCode': 'INR',
  'Nominal': 10,
  'Name': 'Индийских рупий',
  'Value': 10.307,
  'Previous': 10.3597},
 'KZT': {'ID': 'R01335',
  'NumCode': '398',
  'CharCode': 'KZT',
  'Nominal': 100,
  'Name': 'Казахстанских тенге',
  'Value': 17.8025,
  'Previous': 17.7835},
 'CAD': {'ID': 'R01350',
  'NumCode': '124',
  'CharCode': 'CAD',
  'Nominal': 1,
  'Name': 'Канадский доллар',
  'Value': 61.2378,
  'Previous': 61.1186},
 'KGS': {'ID': 'R01370',
  'NumCode': '417',
  'CharCode': 'KGS',
  'Nominal': 100,
  'Name': 'Киргизских сомов',
  'Value': 90.9734,
  'Previous': 90.906},
 'CNY': {'ID': 'R01375',
  'NumCode': '156',
  'CharCode': 'CNY',
  'Nominal': 1,
  'Name': 'Китайский юань',
  'Value': 11.7647,
  'Previous': 11.7728},
 'MDL': {'ID': 'R01500',
  'NumCode': '498',
  'CharCode': 'MDL',
  'Nominal': 10,
  'Name': 'Молдавских леев',
  'Value': 43.1093,
  'Previous': 43.0012},
 'NOK': {'ID': 'R01535',
  'NumCode': '578',
  'CharCode': 'NOK',
  'Nominal': 10,
  'Name': 'Норвежских крон',
  'Value': 90.6573,
  'Previous': 90.8954},
 'PLN': {'ID': 'R01565',
  'NumCode': '985',
  'CharCode': 'PLN',
  'Nominal': 1,
  'Name': 'Польский злотый',
  'Value': 20.2131,
  'Previous': 20.1193},
 'RON': {'ID': 'R01585F',
  'NumCode': '946',
  'CharCode': 'RON',
  'Nominal': 1,
  'Name': 'Румынский лей',
  'Value': 18.6368,
  'Previous': 18.6181},
 'XDR': {'ID': 'R01589',
  'NumCode': '960',
  'CharCode': 'XDR',
  'Nominal': 1,
  'Name': 'СДР (специальные права заимствования)',
  'Value': 109.8207,
  'Previous': 109.8652},
 'SGD': {'ID': 'R01625',
  'NumCode': '702',
  'CharCode': 'SGD',
  'Nominal': 1,
  'Name': 'Сингапурский доллар',
  'Value': 57.5005,
  'Previous': 57.521},
 'TJS': {'ID': 'R01670',
  'NumCode': '972',
  'CharCode': 'TJS',
  'Nominal': 10,
  'Name': 'Таджикских сомони',
  'Value': 67.6773,
  'Previous': 67.6207},
 'TRY': {'ID': 'R01700J',
  'NumCode': '949',
  'CharCode': 'TRY',
  'Nominal': 10,
  'Name': 'Турецких лир',
  'Value': 94.7074,
  'Previous': 94.4785},
 'TMT': {'ID': 'R01710A',
  'NumCode': '934',
  'CharCode': 'TMT',
  'Nominal': 1,
  'Name': 'Новый туркменский манат',
  'Value': 22.0789,
  'Previous': 22.0604},
 'UZS': {'ID': 'R01717',
  'NumCode': '860',
  'CharCode': 'UZS',
  'Nominal': 10000,
  'Name': 'Узбекских сумов',
  'Value': 73.6801,
  'Previous': 73.5751},
 'UAH': {'ID': 'R01720',
  'NumCode': '980',
  'CharCode': 'UAH',
  'Nominal': 10,
  'Name': 'Украинских гривен',
  'Value': 27.6654,
  'Previous': 27.5126},
 'CZK': {'ID': 'R01760',
  'NumCode': '203',
  'CharCode': 'CZK',
  'Nominal': 10,
  'Name': 'Чешских крон',
  'Value': 35.2878,
  'Previous': 35.4961},
 'SEK': {'ID': 'R01770',
  'NumCode': '752',
  'CharCode': 'SEK',
  'Nominal': 10,
  'Name': 'Шведских крон',
  'Value': 90.2217,
  'Previous': 89.7203},
 'CHF': {'ID': 'R01775',
  'NumCode': '756',
  'CharCode': 'CHF',
  'Nominal': 1,
  'Name': 'Швейцарский франк',
  'Value': 83.3503,
  'Previous': 83.0473},
 'ZAR': {'ID': 'R01810',
  'NumCode': '710',
  'CharCode': 'ZAR',
  'Nominal': 10,
  'Name': 'Южноафриканских рэндов',
  'Value': 52.8815,
  'Previous': 53.1933},
 'KRW': {'ID': 'R01815',
  'NumCode': '410',
  'CharCode': 'KRW',
  'Nominal': 1000,
  'Name': 'Вон Республики Корея',
  'Value': 68.877,
  'Previous': 69.0666},
 'JPY': {'ID': 'R01820',
  'NumCode': '392',
  'CharCode': 'JPY',
  'Nominal': 100,
  'Name': 'Японских иен',
  'Value': 70.4324,
  'Previous': 70.4345}}

In [14]:
curr = Rate()
a = curr.exchange_rates()

def get_maximum(data_object):
    maximum_value = 0
    result_currency = ''
    for currency in data_object:
        if data_object[currency]['Value']/data_object[currency]['Nominal'] > maximum_value:
            maximum_value = data_object[currency]['Value']/data_object[currency]['Nominal']
            result_currency = currency
    return data_object[result_currency]['Name']

get_maximum(a)

'СДР (специальные права заимствования)'

In [ ]:
# Задание 2

In [28]:
class Rate:
    def __init__(self, format_='value', diff=False):
        self.format = format_
        self.diff = diff
    
    def exchange_rates(self):
        r = requests.get('https://www.cbr-xml-daily.ru/daily_json.js')
        return r.json()['Valute']
    
    def make_format(self, currency):
        response = self.exchange_rates()
        
        if currency in response:
            if self.format == 'full':
                return response[currency]
            
            if self.format == 'value':
                if self.diff:
                    return response[currency]['Value'] - response[currency]['Previous']
                else:
                    return response[currency]['Value']
        
        return 'Err'
    
    def eur(self):
        return self.make_format('EUR')
    
    def usd(self):
        return self.make_format('USD')
    def dkk(self):
        return self.make_format('DKK')
    
Rate(diff=True).dkk()

0.015499999999999403

In [ ]:
# Задание 3

In [2]:
class Employee:
    def __init__(self, name, seniority):
        self.name = name
        self.seniority = seniority
        
        self.grade = 1
    
    def grade_up(self):
        """Повышает уровень сотрудника"""
        self.grade += 1
    
    def publish_grade(self):
        """Публикация результатов аккредитации сотрудников"""
        print(self.name, self.grade)
    
    def check_if_it_is_time_for_upgrade(self):
        pass

In [20]:
from math import floor
class Designer(Employee):
    def __init__(self, name, seniority, raising=2):
        super().__init__(name, seniority)
        self.raising = raising;

    
    def grade(self):
        return floor((self.raising * 2 + self.seniority) / 7)
    
    def give_a_raising(self):
        print ('Повышение на 1 грейд')
        self.raising += 1
        
    def check_if_it_is_time_for_upgrade(self):
        self.seniority += 1

        return self.publish_grade()
        
elena = Designer('Елена',seniority=2);

for i in range(20):
    elena.check_if_it_is_time_for_upgrade()
    
for i in range(5):
    elena.give_a_raising()
for i in range(20):
    elena.check_if_it_is_time_for_upgrade()

Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Повышение на 1 грейд
Повышение на 1 грейд
Повышение на 1 грейд
Повышение на 1 грейд
Повышение на 1 грейд
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1
Елена 1